// src/components/docs/library-card.tsx
import { GitHubIcon } from '@/components/ui/github-icon'
import { Button } from '@/components/ui/button'
import { getLibrarySlug } from '@/lib/libraries'

interface Library {
  name: string
  stars: number
  description: string
  deprecated?: boolean
}

interface LibraryCardProps {
  library: Library
  hideTitle?: boolean
}

export function LibraryCard({ library, hideTitle = false }: LibraryCardProps) {
  // Don't render deprecated libraries
  if (library.deprecated) {
    return null
  }

  const librarySlug = getLibrarySlug(library.name)
  const libraryUrl = `/library/${librarySlug}`

  return (
    <div className="border border-muted rounded-lg px-4 py-3">
      <div className={`flex items-center ${hideTitle ? 'justify-end' : 'justify-between'} mb-2`}>
        {!hideTitle && <h4 className="font-medium text-[10px]">{library.name}</h4>}
        <div className="flex items-center gap-1 text-xs text-muted-foreground border border-muted rounded-lg px-2 py-1 hover:bg-muted/50 transition-colors">
          <GitHubIcon size={12} />
          <span className="font-medium">{library.stars}</span>
        </div>
      </div>
      <p className="text-[10px] text-muted-foreground leading-relaxed mb-3">{library.description}</p>
      <Button asChild variant="outline" size="sm">
        <a href={libraryUrl}>
          Learn More
        </a>
      </Button>
    </div>
  )
}

// src/components/mdx/LibraryCard.svelte
<script lang="ts">
	import { Star } from 'lucide-svelte';

	export let name: string = '';
	export let description: string = '';
	export let githubUrl: string = '';
	export let stars: number = 0;
	export let libraryUrl: string = '';

	const safeId = name
		.toLowerCase()
		.replace(/[^a-z0-9]+/g, '-')
		.replace(/(^-|-$)/g, '');
</script>

<a href={libraryUrl} class="library-card">
	<div class="card-header">
		<h3 class="title" id={safeId}>
			{name}
		</h3>
		<div class="stats">
			<button class="stars" onclick={(e) => { e.preventDefault(); e.stopPropagation(); window.open(githubUrl, '_blank'); }}>
				<Star size={14} />
				{stars}
			</button>
		</div>
	</div>
	<div class="content">
		<p>{description}</p>
	</div>
</a>

<style lang="postcss">
	.library-card {
		@apply block rounded-lg border border-[#EDEDF0] dark:border-neutral-800 p-4 transition-all duration-300 ease-in-out hover:scale-[1.02] hover:shadow-lg bg-white dark:bg-[#121212]/50 cursor-pointer no-underline hover:no-underline;
	}

	.card-header {
		@apply mb-2 flex items-start justify-between gap-3;
	}

	.title {
		@apply text-[16px] font-semibold leading-[20px] tracking-[-0.0045em] text-[#19191C] dark:text-white;
	}

	.stats {
		@apply flex items-center gap-2;
	}

	.stars {
		@apply flex items-center gap-1 text-xs text-[#666687] dark:text-gray-400 bg-[#FAFAFB] dark:bg-neutral-800/50 px-2 py-1 rounded-md hover:bg-[#F0F0F0] dark:hover:bg-neutral-800 transition-colors duration-200 border-0 cursor-pointer;
	}

	.content {
		@apply text-[14px] leading-[18px] tracking-[-0.0045em] text-[#666687] dark:text-gray-400;
	}

	.content :global(p) {
		@apply m-0;
	}
</style>
